obstacle_range: 3.5
raytrace_range: 2.8
footprint: [[-0.445, -0.35], [-0.445, 0.35], [0.545, 0.35], [0.545, -0.35]]
# robot_radius: 0.3

observation_sources: laser_scan_sensor point_cloud_sensor

laser_scan_sensor: {sensor_frame: laser, data_type: LaserScan, topic: /ebot/laser/scan, marking: true, clearing: true}

point_cloud_sensor: {sensor_frame: laser, data_type: PointCloud, topic: /camera2/depth/img_raw, marking: true, clearing: true}

# transform_tolerance: 2.5