local_costmap:
  global_frame: odom
  robot_base_frame: ebot_base
  update_frequency: 3.5
  publish_frequency: 1.0
  static_map: false
  rolling_window: true
  width: 6.0
  height: 6.0
  resolution: 0.02
  inflation_radius: 0.12