controller_list:
  - name: fake_arm_planning_grp_controller
    type: $(arg fake_execution_type)
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: fake_gripper_planning_group_controller
    type: $(arg fake_execution_type)
    joints:
      - gripper_finger1_joint
initial:  # Define initial robot poses per group
  - group: arm_planning_grp
    pose: allZero
  - group: gripper_planning_group
    pose: open